### ISSUE TITLE
Show and hide of series not working correctly when there is more than 1 chart on the page

### ISSUE THREAD

**Issue by nickverschueren** [apexcharts/Blazor-ApexCharts#115]
Scenario: I have 4 charts on the page and only the first is showing a legend, each showing different aspects of the same devices. All the charts are grouped in a single group. 

Requirement: I want to hide corresponding series on all charts when the legend on the first chart is clicked.

Expected: When I handle the OnLegendClicked event on the first chart and call the Show() or Hide() methods on the corresponding series on the other charts, then all these charts should be showing and hiding the same series on all charts.

Result: Only the first chart is updated.

Further result: If I give the series on all charts unique names (Guid) and I try this again, then I get a Javascript interop error:
`Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'getAttribute')
TypeError: Cannot read properties of null (reading 'getAttribute')
    at t.value (https://localhost:49010/_content/Blazor-ApexCharts/js/apex-charts.min.js:7:94610)
    at t.value (https://localhost:49010/_content/Blazor-ApexCharts/js/apex-charts.min.js:7:95400)
    at t.value (https://localhost:49010/_content/Blazor-ApexCharts/js/apex-charts.min.js:15:48327)
    at Object.hideSeries (https://localhost:49010/_content/Blazor-ApexCharts/js/blazor-apex-charts.js:182:19)
    at https://localhost:49010/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:49010/_framework/blazor.server.js:1:3475)
    at https://localhost:49010/_framework/blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:49010/_framework/blazor.server.js:1:71987)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at ApexCharts.ApexChart`1.HideSeriesAsync(String seriesName)
   at ApexCharts.ApexBaseSeries`1.Hide()
   at Charlie.Web.Pages.Analytics.Index.<>c__DisplayClass65_0.<<OnTemperatureChartLegendClicked>b__2>d.MoveNext()`

It seems to me like there is a scoping issue whereby it cannot find the correct series within the DOM, because it searches in the context of the first chart and not the chart to which the series belongs.

**Comment by joadan** [comment]
Hi,
Thank you for reporting.

I'll try to look into this as soon as I can.

**Comment by joadan** [comment]
I have added a quick sample.. https://apexcharts.github.io/Blazor-ApexCharts/methods/multi-charts
Does this make sense?

**Comment by nickverschueren** [comment]
Yes, indeed - although our case uses dynamically created series. Every device is a series in each chart.
While trying to adapt your sample for this case I noticed that I was setting the wrong chart on the series, so that is why it was going wrong.
Maybe you should consider doing a couple of samples where the series are created in code, because this was not so easy to figure out.
