### ISSUE TITLE
Unhandled exception rendering component: Cannot access a disposed object.

### ISSUE THREAD

**Issue by LiamMorrow** [apexcharts/Blazor-ApexCharts#338]
G'day,
I've noticed this issue with Blazor ApexCharts running in WebAssembly when a chart is rendered, then the page is navigated away.  It is not always reproducible, but when rapidly navigating it can happen pretty often.

On this specific page it's rendering a line graph.
[Here](https://github.com/LiamMorrow/LiftLog/blob/main/LiftLog.Ui/Shared/Presentation/StatGraphCardContent.razor) is the code which I am using to render the Apex Chart. It's driven by [this page](https://github.com/LiamMorrow/LiftLog/blob/main/LiftLog.Ui/Pages/StatsPage.razor) which basically just uses the  `CardList` component to loop through some data and render line charts.

Logs [github action run](https://github.com/LiamMorrow/LiftLog/actions/runs/6870892593/job/18686675305?pr=51#step:7:192):
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot access a disposed object.
      Object name: 'Microsoft.JSInterop.WebAssembly.WebAssemblyJSObjectReference'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.JSInterop.WebAssembly.WebAssemblyJSObjectReference'.
   at Microsoft.JSInterop.Implementation.JSObjectReference.ThrowIfDisposed()
   at Microsoft.JSInterop.Implementation.JSObjectReference.InvokeAsync[IJSVoidResult](String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at ApexCharts.Internal.JSHandler`1.<RenderChartAsync>d__6[[LiftLog.Ui.Models.DatedRecordedExercise, LiftLog.Ui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at ApexCharts.ApexChart`1.<RenderChartAsync>d__175[[LiftLog.Ui.Models.DatedRecordedExercise, LiftLog.Ui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at ApexCharts.ApexChart`1.<OnAfterRenderAsync>d__139[[LiftLog.Ui.Models.DatedRecordedExercise, LiftLog.Ui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)", source: http://127.0.0.1:5000/_framework/blazor.webassembly.js (1)
```

It manifests itself as a top level blazor error, seen here as a cypress screenshot (note that we're not on the page which displays the graphs as it occurs after navigating away)

![Settings -- When a user restores data -- and updates the imperial units setting -- should display weights in the correct units on all pages (failed)](https://github.com/apexcharts/Blazor-ApexCharts/assets/13741016/c58f6a67-2494-4fde-8533-331db3ad4959)

Just wondering if you have any tips on how I might handle this.  I *think* I could handle it with an `ErrorBoundary` but thought it would be good to report the issue

**Comment by joadan** [comment]
Thank you for reporting, I will take a look asap.

**Comment by joadan** [comment]
Hello, 

Could you please upgrade to version 2.1.0, I believe I have fixed the issue.

**Comment by LiamMorrow** [comment]
That seems to have done the trick! Thank you :)

**Comment by neozhu** [comment]
In my project, I am encountering the same issue. My project has been upgraded to .NET 8 and is using RenderMode.InteractiveServer. The first load works fine, but when navigating back to the page for the second time, it throws an error: 'jsObjectReference'.
