### ISSUE TITLE
jsObjectReference occasionally returning null when calling UpdateOptionsAsync or UpdateSeriesAsync

### ISSUE THREAD

**Issue by mwerberacs** [apexcharts/Blazor-ApexCharts#350]
I recently upgraded the ApexCharts nuget package from 0.92.0-beta to 2.1.0. Upon doing so, my team is now encountering consistent errors being thrown when calling UpdateOptionsAsync or UpdateSeriesAsync due to a null value.

> blazor.server.js:1 [2023-12-01T15:32:01.589Z] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at ApexCharts.ApexChart`1.InvokeVoidJsAsync(String identifier, Object[] args)
   at ApexCharts.ApexChart`1.UpdateSeriesAsync(Boolean animate)
   at ApprenticeshipComplianceSystem.Modules.ApprenticeManager.ApprenticeEvaluations.OnParametersSetAsync() in C:\Users\Mariah.Werber\source\repos\ApprenticeshipComplianceSystem\ApprenticeshipComplianceSystem\Modules\Managers\ApprenticeManager\TabPanels\Evaluations\ApprenticeEvaluations.razor:line 627
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Using a `try/catch` stops the app from crashing and the charts update as normal, but I have a function that prints the error message in the devtools console manually when it falls through to `catch` and I can see the null value error still happens. Reverting back to 0.92.0-beta fixes this issue entirely.

**Comment by matt-entrekin** [comment]
I had similar issues related to the series being empty. It was hard to debug because the underlying code in Blazor-ApexCharts using async await. When debugging the Blazor-ApexCharts code, what I saw was a chart's `.Series` that was an empty collection later becoming `null`. That meant I couldn't always rely on `Series.Any()` to prevent the errors.

I ended up using a heavy-handed approach of replacing my code's references to ApexChart with my custom subclass that prevents the errors.

```cs
public class MyApexChart<TItem> : ApexChart<TItem> where TItem : class
{
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        try
        {
            // ApexCharts throws when trying to render a chart without a series.
            if (Series.Any())
            {
                await base.OnAfterRenderAsync(firstRender);
            }
        }
        catch
        {
        }
    }
}
```

**Comment by MichaelCastano** [comment]
Just came across the exact same issue, updated from 0.9.13-beta to 2.1.0.

@mwerberacs where did you put the `try/catch`? Just around the two Update calls?

**Comment by Alywan** [comment]
Where do i need to put the try/catch ?

My code breaks here :

            await Chart!.UpdateSeriesAsync(true);

**Comment by joadan** [comment]
Hi, I have added a guard in Release v2.2.0.

Would be great if you could try it out and let me know if it resolves the issue.

Thank you
