### ISSUE TITLE
Custom ToolTip Is failing with JS Data Pointer Enter Invoking Execption.

### ISSUE THREAD

**Issue by junaidiqbal0022** [apexcharts/Blazor-ApexCharts#497]
blazor.web.js:1 Uncaught (in promise) Error: There was an exception invoking 'JSDataPointEnter'. For more details turn on detailed exceptions in 'CircuitOptions.DetailedErrors'
    at y.endInvokeDotNetFromJS (blazor.web.js:1:3305)
    at gn._invokeClientMethod (blazor.web.js:1:62730)
    at gn._processIncomingData (blazor.web.js:1:60119)
    at connection.onreceive (blazor.web.js:1:53760)
    at i.onmessage (blazor.web.js:1:81866)

**Comment by junaidiqbal0022** [comment]
Was resolved after deleting bin and obj folders and re-building the solution.

**Comment by junaidiqbal0022** [comment]
Was resolved after deleting bin and obj folders and re-building the solution.
