### ISSUE TITLE
Apex Chart Service does not work in Blazor WASM

### ISSUE THREAD

**Issue by Sane7222** [apexcharts/Blazor-ApexCharts#538]
**Description:**

Encountering a type resolution error when adding `builder.Services.AddApexCharts()` to the Blazor WASM program file in .NET 8.

**Steps to Reproduce:**
1. Add `builder.Services.AddApexCharts()` to the Blazor WASM program file
2. Run the application

**Specs:**
- .NET 8
- Blazor WASM
- Blazor-ApexCharts v4.0.0

**Error Message:**

    `ManagedError: Could not resolve type with token 010000b2 from typeref (expected class 'ApexCharts.ApexChartsExtensions' in assembly 'Blazor-ApexCharts, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null')
    at Jn (c:\Users\admin1\source\repos\website\website\website\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\81cabf2857a01351e5ab578947c7403a5b128ad1\src\mono\wasm\runtime\marshal-to-js.ts:349:18)
    at kr(c:\Users\admin1\source\repos\website\website\website\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\81cabf2857a01351e5ab578947c7403a5b128ad1\src\mono\wasm\runtime\invoke-cs.ts:277:19)
    at l.javaScriptExports.call_entry_point(c: \Users\admin1\source\repos\website\website\website\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\81cabf2857a01351e5ab578947c7403a5b128ad1\src\mono\wasm\runtime\managed - exports.ts:60:13)
    at Object.Fc[as runMain](c: \Users\admin1\source\repos\website\website\website\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\81cabf2857a01351e5ab578947c7403a5b128ad1\src\mono\wasm\runtime\run.ts:44:45)
    at Object.callEntryPoint(:1:156271)
    at ti(https://localhost:7204/_framework/blazor.web.js:1:163775) {superStack: {…}, managed_stack: '   at System.Runtime.CompilerServices.Asy…t:7204/_framework/blazor.web.js:1:163775)', stack: <accessor>, message: 'Could not resolve type with token 010000b2 f….0.0, Culture=neutral, PublicKeyToken=null')', Symbol(wasm js_owned_gc_handle): 38}`

**Comment by joadan** [comment]
Hi,

Do you have AOT enabled?

**Comment by Sane7222** [comment]
Hi,

No, I do not have AOT enabled on my project.

I would also like to give more context on the issue. I upgraded directly from Blazor-ApexCharts 3.4.0 -> 4.0.0 with no other changes to my project. Even without adding `builder.Services.AddApexCharts()` the package errors out when navigating to a page with an Apex Chart.

Could it be that there were breaking changes in v4.0.0 that I may have missed?

**Comment by joadan** [comment]
Hi, 

Just to be clear this happens in debug mode, right?
Have you tried to clean your solution?

**Comment by Sane7222** [comment]
Hi,

Yes, this was occurring in debug mode.

Cleaning the solution was all I needed to do. Sorry about that. Thanks for the help!
